### ISSUE TITLE
maps

### ISSUE THREAD

**Issue by holtzy** [holtzy/R-graph-gallery#91]
https://twitter.com/Paula_Moraga_/status/1646386958107811840

**Comment by dieghernan** [comment]
Hi @holtzy 

Thanks for the website, I went into R some years ago following your examples, very grateful.

I think the map-related section needs to be fully revamped. Since the website was created, there were major changes in the R spatial ecosystem:
- Some of the packages you used (i.e. rgdal) are [going to be retired](https://www.r-bloggers.com/2022/04/r-spatial-evolution-retirement-of-rgdal-rgeos-and-maptools/) or have been already marked as superseeded (as cartography). 
- New "golden standards" as sf and terra packages are not mentioned. These packages are well supported in ggplot2 and now making maps is much easier.
- Other packages that may be of interest ("maptiles" for static maps) have been developed.

I think I can contribute by updating some sections. For example, see in https://gis.stackexchange.com/questions/460615/using-a-downloaded-shapefile-in-ggplot2-and-r-readogr-error/460796#460796 how this page https://r-graph-gallery.com/168-load-a-shape-file-into-r.html can be updated by using `sf` and native support of `ggplot2`:

``` r
# Download the shapefile

tempzip <- tempfile(fileext = ".zip")

download.file("http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip" , 
              destfile=tempzip)

# Unzip this file. You can do it with R (as below)

unzip(tempzip, exdir = tempdir())

#  -- > You now have 4 files. One of these files is a .shp file! (TM_WORLD_BORDERS_SIMPL-0.3.shp)

# Read this shape file with the sf library. 
library(sf)

my_sf <- st_read(file.path(tempdir(), "TM_WORLD_BORDERS_SIMPL-0.3.shp"))

# Basic plot of this shape file:
par(mar=c(0,0,0,0))
plot(st_geometry(my_sf), col="#f2f2f2", bg="skyblue", lwd=0.25, border=0 )
```

![](https://i.imgur.com/PdcceJJ.png)

``` r


# ggplot2 handles 'sf' natively

# Plot it
library(ggplot2)
ggplot(my_sf) +
  geom_sf(fill="#69b3a2", color="white") +
  theme_void() 
```

![](https://i.imgur.com/3D23NwO.png)

<sup>Created on 2023-06-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
